Document fixes
Mbed-TLS/mbedtls-docs pull request #146
Opened 2024-05-08 13:43 UTC by eleuzi01

- fixed expired image link
- fixed title headers

2024-05-08 14:10 UTC, paul-elliott-arm commented on kb/how-to/mbedtls-tutorial.md
> +![Mbed TLS Stack.png](https://web.archive.org/web/20210921191453/https://mbed-tls-docs-images.s3.amazonaws.com/mbedtls-stack.png)
I'm unsure of the reason it was in an S3 bucket in the first place tbh - @bensze01 was this you?

2024-05-29 10:57 UTC, gilles-peskine-arm requested changes
The title level change is incomplete.

2024-05-29 10:57 UTC, gilles-peskine-arm commented on kb/how-to/reduce-polarssl-memory-and-storage-footprint.md
> +## Memory footprint
Please downgrade the subsections and subsubsections as well.

2024-05-30 09:33 UTC, gilles-peskine-arm approved these changes
LGTM

2024-05-30 09:33 UTC, merged