Do not use loose modules
Mbed-TLS/mbedtls-docs pull request #45
Opened 2022-08-30 20:20 UTC by gilles-peskine-arm

The development team has not actively supported loose modules for several
years and discourages its use. Replace the instructions for using loose
modules by instructions for using the original mbedtls source tree with
a minimal configuration.

2022-08-31 16:17 UTC, bensze01 requested changes
Just a couple of typos and nitpicks - aside from that, this looks good to me.

2022-08-31 16:17 UTC, bensze01 commented on kb/how-to/using-loose-modules-without-the-full-library.md
> +cc -I configs -I external/mbedtls/include …
Ditto
```suggestion
$ cc -I configs -I external/mbedtls/include …
```

2022-08-31 16:17 UTC, bensze01 commented on kb/how-to/using-loose-modules-without-the-full-library.md
>  ```
Ditto
```suggestion
```console
```

2022-08-31 16:17 UTC, bensze01 commented on kb/how-to/using-loose-modules-without-the-full-library.md
> +cc -DMBEDTLS_CONFIG_FILE='"my_mbedtls_config.h"' -I configs -I external/mbedtls/include …
Ditto
```suggestion
$ cc -DMBEDTLS_CONFIG_FILE='"my_mbedtls_config.h"' -I configs -I external/mbedtls/include …
```

2022-08-31 16:17 UTC, bensze01 commented on kb/how-to/using-loose-modules-without-the-full-library.md
> +If you prefer, you can include the Mbed TLS source files in your own build scripts. All the library code is in the `library` subdirectory, except for aa few features that use code from the `3rdparty`
Typo:
```suggestion
If you prefer, you can include the Mbed TLS source files in your own build scripts. All the library code is in the `library` subdirectory, except for a few features that use code from the `3rdparty` directory tree. All the public headers are in the `include` directory tree.
```

2022-09-08 08:59 UTC, tom-cosgrove-arm commented on kb/how-to/using-loose-modules-without-the-full-library.md
>  You decide to use HMAC\_DRBG, and use SHA-512 as the hash function both for entropy and for the DRBG. As a conseqence, you write the following configuration file:
Can you fix the spelling of `conseqence` while you are nearby, please?

2022-09-08 15:08 UTC, bensze01 approved these changes
Thanks! Looks good to me.

2022-09-08 15:22 UTC, tom-cosgrove-arm approved these changes
LGTM

2022-09-08 15:23 UTC, merged